### ISSUE TITLE
Getting "exec /init: exec format error" in logs when trying to start the "RTL_433 to MQTT Bridge with Interlogix auto-discovery" add-on

### ISSUE THREAD

**Issue by gean13** [yannicklarrivee/homeassistant-addons-master#31]
**Describe the bug**
I'm getting the error "exec /init: exec format error" when I try to start the "RTL_433 to MQTT Bridge with Interlogix auto-discovery" add-on. With or without filling in the configuration.

**To Reproduce**
1. Install "RTL_433 to MQTT Bridge with Interlogix auto-discovery" in Home Assistant
2. Click on Start.
3. Go to Log
4. See error -- "exec /init: exec format error"

**Expected behavior**
Add-on should start without issue.

**Screenshots**
See screenshots of the error and config setup

![HA Add-On error](https://github.com/yannicklarrivee/homeassistant-addons-master/assets/68611273/2824e4fd-bf09-401f-a38e-e3a26f3caf43)

![HA Add-On configuration](https://github.com/yannicklarrivee/homeassistant-addons-master/assets/68611273/5b3674f9-a36f-4767-937f-7ee977baf437)

**Desktop:**
 - Home Assistant running in a VM (Hass.io) [(amd64)]
 - Home Assistant Version Info:
 - Core: 2024.3.1
 - Supervisor 2024.03.0
 - Operating System 12.1
 - Frontend 20240307.0

**Comment by gean13** [comment]
I looked up the error and seems to be from having a mismatch in architecture. I compared some of the code to the [rtl_433-hass-addons](https://github.com/pbkhrv/rtl_433-hass-addons) repository and it might be the config.yml having `armv7` set in the `image` field? Could that be causing the armv7 to be used instead of the amd64 for my system? 
![image](https://github.com/yannicklarrivee/homeassistant-addons-master/assets/68611273/8d37138d-3343-4a2b-992c-3beb57038bfb)
-----Versus-----
![image](https://github.com/yannicklarrivee/homeassistant-addons-master/assets/68611273/f6254905-37f9-45da-94c1-ad38be08a969)
with "{arch}" set in the` image` field.

**Comment by gean13** [comment]
Forked and was able to get the amd64 version installed and working. Appreciate your hard work.

**Comment by yannicklarrivee** [comment]
I had hardcoded that for a specific device and was planning to fix this. I thought I was the only one using this! :-D
